# ESPKyoGate Alarm Control Panel Package
# https://github.com/lorenzo-deluca/espkyogate
#
# This package creates a Home Assistant alarm_control_panel entity
# that integrates with your ESPKyoGate device.
#
# ============================================================================
# CONFIGURATION INSTRUCTIONS
# ============================================================================
#
# 1. Copy this file to your Home Assistant config/packages/ directory
#    (create the packages folder if it doesn't exist)
#
# 2. Enable packages in your configuration.yaml by adding:
#    homeassistant:
#      packages: !include_dir_named packages
#
# 3. Customize the VARIABLES section below to match your setup
#
# 4. Add your alarm code to secrets.yaml:
#    alarmcode: "{{ value == 'YOUR_CODE' }}"
#
# 5. Restart Home Assistant
#
# ============================================================================
# VARIABLES - MODIFY THESE TO MATCH YOUR SETUP
# ============================================================================
# Change these values to match your ESPKyoGate configuration.
# All variables are defined here for easy customization.

homeassistant:
  customize:
    # This section stores your configuration variables as entity attributes
    # for reference. The actual values are used in the templates below.
    package.espkyogate_alarm_panel:
      # ---- AREA CONFIGURATION ----
      # Area numbers for your alarm zones (1-8 depending on your KYO model)
      area_1_number: &area_1 1              # Perimeter area number
      area_2_number: &area_2 2              # Internal area number
      
      # Binary sensors for area arm status
      # Change these to match your ESPKyoGate entity IDs
      area_1_sensor: &area_1_sensor "binary_sensor.espkyogate_ins_totale_area_1"
      area_2_sensor: &area_2_sensor "binary_sensor.espkyogate_ins_totale_area_2"
      
      # ---- ZONE EXCLUSION CONFIGURATION ----
      # Zone numbers for exclusion switches (1-32 depending on your KYO model)
      zone_1_number: &zone_1 1
      zone_2_number: &zone_2 2
      
      # Binary sensors for zone exclusion status
      zone_1_sensor: &zone_1_sensor "binary_sensor.espkyogate_escl_zona_1"
      zone_2_sensor: &zone_2_sensor "binary_sensor.espkyogate_escl_zona_2"

# ============================================================================
# ALARM CONTROL PANEL TEMPLATE
# ============================================================================

template:
  - alarm_control_panel:
      - name: "Allarme Casa"
        unique_id: espkyogate_alarm_panel
        
        # State logic:
        # - armed_night: Only perimeter armed (Area 1 ON, Area 2 OFF)
        # - armed_away: Both areas armed (Area 1 ON, Area 2 ON)
        # - disarmed: All areas disarmed
        #
        # NOTE: Update the binary_sensor entity IDs below to match
        # the area_1_sensor and area_2_sensor variables defined above
        state: >-
          {% set area_1_armed = is_state('binary_sensor.espkyogate_ins_totale_area_1', 'on') %}
          {% set area_2_armed = is_state('binary_sensor.espkyogate_ins_totale_area_2', 'on') %}
          {% if area_1_armed and not area_2_armed %}
            armed_night
          {% elif area_1_armed and area_2_armed %}
            armed_away
          {% else %}
            disarmed
          {% endif %}

        # Code format: number = numeric keypad, text = alphanumeric
        code_format: number
        
        # Require code to arm the alarm (set to false for no code on arm)
        code_arm_required: true

        # ARM NIGHT: Arms only Area 1 (perimeter)
        arm_night:
          - condition: template
            value_template: !secret alarmcode
          - action: esphome.espkyogate_arm_area
            data:
              arm_type: 1        # 1 = Total arm, 2 = Partial arm
              area: *area_1      # Uses area_1_number variable
              specific_area: 0   # 0 = arm this area and disarm others

        # ARM AWAY: Arms both Area 1 and Area 2 (full protection)
        arm_away:
          - condition: template
            value_template: !secret alarmcode
          - action: esphome.espkyogate_arm_area
            data:
              arm_type: 1        # 1 = Total arm, 2 = Partial arm
              area: *area_1      # Uses area_1_number variable
              specific_area: 0   # Arm this area and disarm others
          - delay:
              seconds: 2         # Wait for area 1 to be armed
          - action: esphome.espkyogate_arm_area
            data:
              arm_type: 1        # 1 = Total arm, 2 = Partial arm
              area: *area_2      # Uses area_2_number variable
              specific_area: 1   # Arm only this area without changing others

        # DISARM: Disarms all areas
        disarm:
          - condition: template
            value_template: !secret alarmcode
          - action: esphome.espkyogate_disarm_area
            data:
              area: 0            # 0 = all areas
              specific_area: 0   # 0 = disarm all areas

# ============================================================================
# OPTIONAL: ZONE EXCLUSION SWITCHES
# ============================================================================
# Uncomment the section below and duplicate switches as needed for each zone.
# The zone numbers use the variables defined at the top of this file.
#
# NOTE: Update the binary_sensor entity IDs in the state templates to match
# the zone_1_sensor and zone_2_sensor variables defined above

#   - switch:
#       - name: "Esclusione Zona 1"
#         unique_id: espkyogate_exclude_zone_1
#         state: "{{ is_state('binary_sensor.espkyogate_escl_zona_1', 'on') }}"
#         turn_on:
#           - action: esphome.espkyogate_exclude_zone
#             data:
#               zone_number: *zone_1    # Uses zone_1_number variable
#         turn_off:
#           - action: esphome.espkyogate_include_zone
#             data:
#               zone_number: *zone_1    # Uses zone_1_number variable
#
#       - name: "Esclusione Zona 2"
#         unique_id: espkyogate_exclude_zone_2
#         state: "{{ is_state('binary_sensor.espkyogate_escl_zona_2', 'on') }}"
#         turn_on:
#           - action: esphome.espkyogate_exclude_zone
#             data:
#               zone_number: *zone_2    # Uses zone_2_number variable
#         turn_off:
#           - action: esphome.espkyogate_include_zone
#             data:
#               zone_number: *zone_2    # Uses zone_2_number variable
